Model creation cc
inaki92/TheCocktailApp pull request #1
Opened 2023-02-08 13:55 UTC by carlosCabrera2

Created the Model
CC @inaki92 @sarisiza @chr1s4ng3l

2023-02-08 14:05 UTC, inaki92 commented
@carlosCabrera2 please add the reviewers to the PR in the left side there is that option.

2023-02-08 18:54 UTC, inaki92 approved these changes
Make the changes and push the new code.

Also, make sure to use the correct naming for classes.

2023-02-08 18:54 UTC, inaki92 commented on app/build.gradle
> +
No extra spaces here

2023-02-08 18:54 UTC, inaki92 commented on app/src/main/java/com/example/thecocktailsapp/model/CocktailIInfo/CocktailInfo.kt
> +    val drinks: List<DrinkXX>? = listOf()
Does this need to be nullable? and also let's have a better name for the DrinkXX

2023-02-08 18:54 UTC, inaki92 commented on app/src/main/java/com/example/thecocktailsapp/model/CocktailIInfo/DrinkXX.kt
> +    val strDrinkAlternate: Any? = null,
What is Any? let's define the correct data type

2023-02-08 18:54 UTC, inaki92 commented on app/src/main/java/com/example/thecocktailsapp/model/CocktailIInfo/DrinkXX.kt
> +    val strIngredient10: Any? = null,
same here change Any to the real data type

2023-02-08 18:54 UTC, inaki92 commented on app/src/main/java/com/example/thecocktailsapp/model/CocktailIInfo/DrinkXX.kt
> +    val strVideo: Any? = null
If there is a video on youtube...  let's think about playing the video in EXO PLAYER

2023-02-08 18:54 UTC, inaki92 commented on app/src/main/java/com/example/thecocktailsapp/model/CocktailsByName/CocktailsByName.kt
> +    val drinks: List<Drink?>? = null
The Drink as nullable can be omitted

2023-02-08 18:54 UTC, inaki92 commented on app/src/main/java/com/example/thecocktailsapp/model/CocktailsByName/Drink.kt
> +data class Drink(
THis looks the same as the DrinkXX, find out if it is needed, if not remove it

2023-02-09 03:12 UTC, sarisiza approved these changes
Check comments and check
We should only have a single Drink and Cocktails data class

2023-02-09 03:12 UTC, sarisiza commented on app/build.gradle
> +    implementation 'com.google.dagger:dagger-android:2.44.2'
This should be hilt instead of dagger

2023-02-09 14:56 UTC, chr1s4ng3l requested changes
We need to set only the necessary data we do not need extra data unusable.

2023-02-09 14:56 UTC, chr1s4ng3l commented on app/src/main/java/com/example/thecocktailsapp/model/CocktailIInfo/DrinkXX.kt
> +data class DrinkXX(
Duplicated model.
(DrrinkXX and Drink)

2023-02-09 14:56 UTC, chr1s4ng3l commented on app/src/main/java/com/example/thecocktailsapp/model/CocktailsByName/Drink.kt
> +data class Drink(
Duplicated model.
(DrrinkXX and Drink)

2023-02-09 14:58 UTC, chr1s4ng3l approved these changes

2023-02-13 13:38 UTC, carlosCabrera2 reviewed
i made the changes

2023-02-13 13:39 UTC, merged