Added the class CocktailsAppViewModel.kt that has a ViewModel instance from the androidx.lifecycle library
inaki92/TheCocktailApp pull request #11
Opened 2023-02-15 16:15 UTC by luizeth0

Added the class CocktailsAppViewModel.kt that has a ViewModel instance from the androidx.lifecycle library

2023-02-15 18:32 UTC, inaki92 requested changes

2023-02-15 18:32 UTC, inaki92 commented on app/src/main/java/com/example/thecocktailsapp/viewmodule/CocktailsAppViewModel.kt
> +    private val ioDispatcher: CoroutineDispatcher = Dispatchers.IO
Lets have this in the constructor, in order to pass a test dispatcher when testing

2023-02-15 18:32 UTC, inaki92 commented
@luizeth0 please add you unit testing

2023-02-16 02:02 UTC, chr1s4ng3l approved these changes, later dismissed

2023-02-16 03:14 UTC, sarisiza approved these changes, later dismissed
LGTM

2023-02-17 18:07 UTC, chr1s4ng3l approved these changes
lgtm

2023-02-17 18:11 UTC, closed without merging